spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.210.28.177:3306/sell?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell


wechat:
  mpAppId: wxa09cadeeb91c6dce
  mpAppSecret: 601b9c13b702e67a1a8e31d0e0ca4545
  mchId:
  mchKey:
  keyPath:
  notifyUrl: http://localhost/sell/pay/notify #异步通知支付